"""empty message

Revision ID: 646efbf6480b
Revises: 
Create Date: 2020-04-16 20:42:15.699695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646efbf6480b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cadastros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razao', sa.String(length=50), nullable=True),
    sa.Column('fantasia', sa.String(length=50), nullable=True),
    sa.Column('cnpj', sa.Integer(), nullable=True),
    sa.Column('inscricaoestadual', sa.String(length=14), nullable=True),
    sa.Column('inscricaomunicipal', sa.String(length=14), nullable=True),
    sa.Column('telefone', sa.Integer(), nullable=True),
    sa.Column('cep', sa.Integer(), nullable=True),
    sa.Column('rua', sa.String(length=50), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('bairro', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('pais', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('modelo', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('placa', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.Column('datahora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Odss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('pecas', sa.String(length=1000), nullable=True),
    sa.Column('custo', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Odss')
    op.drop_table('agendas')
    op.drop_table('equipamentos')
    op.drop_table('usuarios')
    op.drop_table('clientes')
    op.drop_table('cadastros')
    # ### end Alembic commands ###
